print("Welcome to Security")
import time
time.sleep(0.5)
print ("Loading...")
time.sleep(0.8)
print("12%")
time.sleep(0.8)
print("24%")
time.sleep(1.2)
print("31%")
time.sleep(0.8)
print("46%")
time.sleep(1)
print("51%")
time.sleep(0.8)
print("76%")
time.sleep(0.8)
print("81%")
time.sleep(1.8)
print("99%")
time.sleep(0.8)
print("Connecting to server...")
time.sleep(1)
print("Welcome")
password = input("Input Password: ")
if password =="password":
    time.sleep(0.4)
    print("Loading Database...")
    time.sleep(1)
    print("Press 1 For Maths")
    print("Press 2 for Fun")
    print("press 3 for else")
    print("press 4 for security")
    print("5 to end")
    optiondatabase = input()
    if optiondatabase =="1":
        print("Press 1 for ")
    if optiondatabase =="2":
        print("2")
    if optiondatabase =="3":
        print("3")
    if optiondatabase =="4":
        print("4")
    if optiondatabase =="5":
        print("5")
else:
    print("Incorrect Password")
    print("Self Destructing In 2 Seconds")
    time.sleep(2)
    exit()
